// Code generated by tygo. DO NOT EDIT.

//////////
// source: exclude.go

export enum Exclude {
	ExcludeRetweets = 'retweets',
	ExcludeReplies = 'replies'
}
export type ExcludeList = Exclude[];

//////////
// source: expansions.go

export enum Expansion {
	ExpansionPinnedTweetID = 'pinned_tweet_id',
	ExpansionAttachmentsPollIDs = 'attachments.poll_ids',
	ExpansionAttachmentsMediaKeys = 'attachments.media_keys',
	ExpansionAuthorID = 'author_id',
	ExpansionEntitiesMentionsUsername = 'entities.mentions.username',
	ExpansionGeoPlaceID = 'geo.place_id',
	ExpansionInReplyToUserID = 'in_reply_to_user_id',
	ExpansionReferencedTweetsID = 'referenced_tweets.id',
	ExpansionReferencedTweetsIDAuthorID = 'referenced_tweets.id.author_id',
	ExpansionInvitedUserIDs = 'invited_user_ids',
	ExpansionSpeakerIDs = 'speaker_ids',
	ExpansionCreatorID = 'creator_id',
	ExpansionHostIDs = 'host_ids'
}
export type ExpansionList = Expansion[];

//////////
// source: list_fields.go

export enum ListField {
	ListFieldCreatedAt = 'created_at',
	ListFieldFollowerCount = 'follower_count',
	ListFieldMemberCount = 'member_count',
	ListFieldPrivate = 'private',
	ListFieldDescription = 'description',
	ListFieldOwnerID = 'owner_id'
}
export type ListFieldList = ListField[];

//////////
// source: media_fields.go

export enum MediaField {
	MediaFieldDurationMs = 'duration_ms',
	MediaFieldHeight = 'height',
	MediaFieldMediaKey = 'media_key',
	MediaFieldPreviewImageUrl = 'preview_image_url',
	MediaFieldType = 'type',
	MediaFieldUrl = 'url',
	MediaFieldWidth = 'width',
	MediaFieldPublicMetrics = 'public_metrics',
	MediaFieldNonPublicMetrics = 'non_public_metrics',
	MediaFieldOrganicMetrics = 'organic_metrics',
	MediaFieldPromotedMetrics = 'promoted_metrics',
	MediaFieldAltText = 'alt_text',
	MediaFieldVariants = 'variants'
}
export type MediaFieldList = MediaField[];

//////////
// source: place_fields.go

export enum PlaceField {
	PlaceFieldContainedWithin = 'contained_within',
	PlaceFieldCountry = 'country',
	PlaceFieldCountryCode = 'country_code',
	PlaceFieldFullName = 'full_name',
	PlaceFieldGeo = 'geo',
	PlaceFieldID = 'id',
	PlaceFieldName = 'name',
	PlaceFieldPlaceType = 'place_type'
}
export type PlaceFieldList = PlaceField[];

//////////
// source: poll_fields.go

export enum PollField {
	PollFieldDurationMinutes = 'duration_minutes',
	PollFieldEndDatetime = 'end_datetime',
	PollFieldID = 'id',
	PollFieldOptions = 'options',
	PollFieldVotingStatus = 'voting_status'
}
export type PollFieldList = PollField[];

//////////
// source: space_fields.go

export enum SpaceField {
	SpaceFieldHostIDs = 'host_ids',
	SpaceFieldCreatedAt = 'created_at',
	SpaceFieldCreatorID = 'creator_id',
	SpaceFieldID = 'id',
	SpaceFieldLang = 'lang',
	SpaceFieldInvitedUserIDs = 'invited_user_ids',
	SpaceFieldParticipantCount = 'participant_count',
	SpaceFieldSpeakerIDs = 'speaker_ids',
	SpaceFieldStartedAt = 'started_at',
	SpaceFieldState = 'state',
	SpaceFieldTitle = 'title',
	SpaceFieldUpdatedAt = 'updated_at',
	SpaceFieldScheduledStart = 'scheduled_start',
	SpaceFieldIsTicketed = 'is_ticketed'
}
export type SpaceFieldList = SpaceField[];

//////////
// source: state.go

export enum State {
	StateAll = 'all',
	StateLive = 'live',
	StateScheduled = 'scheduled'
}

//////////
// source: tweet_fields.go

export enum TweetField {
	TweetFieldAttachments = 'attachments',
	TweetFieldAuthorID = 'author_id',
	TweetFieldContextAnnotations = 'context_annotations',
	TweetFieldConversationID = 'conversation_id',
	TweetFieldCreatedAt = 'created_at',
	TweetFieldEntities = 'entities',
	TweetFieldGeo = 'geo',
	TweetFieldID = 'id',
	TweetFieldInReplyToUserID = 'in_reply_to_user_id',
	TweetFieldLang = 'lang',
	TweetFieldNonPublicMetrics = 'non_public_metrics',
	TweetFieldPublicMetrics = 'public_metrics',
	TweetFieldOrganicMetrics = 'organic_metrics',
	TweetFieldPromotedMetrics = 'promoted_metrics',
	TweetFieldPossiblySensitive = 'possibly_sensitive',
	TweetFieldReferencedTweets = 'referenced_tweets',
	TweetFieldReplySettings = 'reply_settings',
	TweetFieldSource = 'source',
	TweetFieldText = 'text',
	TweetFieldWithheld = 'withheld'
}
export type TweetFieldList = TweetField[];

//////////
// source: user_fields.go

export enum UserField {
	UserFieldCreatedAt = 'created_at',
	UserFieldDescription = 'description',
	UserFieldEntities = 'entities',
	UserFieldID = 'id',
	UserFieldLocation = 'location',
	UserFieldName = 'name',
	UserFieldPinnedTweetID = 'pinned_tweet_id',
	UserFieldProfileImageUrl = 'profile_image_url',
	UserFieldProtected = 'protected',
	UserFieldPublicMetrics = 'public_metrics',
	UserFieldUrl = 'url',
	UserFieldUsername = 'username',
	UserFieldVerified = 'verified',
	UserFieldWithheld = 'withheld'
}
export type UserFieldList = UserField[];
