name: Validate

on:
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.number }}/merge

      - name: Setup Bun
        uses: xhyrom/setup-bun@v0.1.3
        with:
          bun-version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get changed files
        uses: Mineflash07/gh-action-get-changed-files@feature/support-pr-target-event
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add json
        run: cp $HOME/files.json ./scripts/validateTags/

      - name: Validate tag
        run: bun run validate
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-sha: ${{ github.event.pull_request.head.sha }}
          pr-number: ${{ github.event.pull_request.number }}